#!/usr/bin/env node
'use strict';

const Compiler = require('../compiler');
const compiler = new Compiler(__dirname);

let bundled = `(() => {
'use strict';
const exports = {};
`;
bundled += compiler.read('index.js', 1, 1);
bundled += `
// EXPORTS
window.CalcGenerations = exports.Generations;
})();`
compiler.compile(bundled);
