#!/usr/bin/env node
'use strict';

const child_process = require('child_process');
const fs = require('fs');
const path = require('path');

const exec = async (cmd, cwd = __dirname) => {
  return new Promise(resolve => {
    child_process.exec(cmd, {cwd}, (error, stdout, stderr) => {
      resolve([error ? error.code : 0, stdout, stderr]);
    });
  });
}

const execOrDie = async (cmd, cwd = __dirname) => {
  console.log(cmd);
  const [error, stdout, stderr ]= await exec(cmd, cwd);
  if (error || stderr) {
    console.error(stderr);
    process.exit(error);
  }
  return stdout;
}

const tree = root => {
  const leaves = [];
  for (const child of fs.readdirSync(root)) {
    const p = path.join(root, child);
    leaves.push(...(fs.lstatSync(p).isDirectory() ? tree(p) : [p]));
  }
  return leaves;
}

// FIXME promisify!
const replace = (file, replacements) => {
	fs.lstat(file, (err, stats) => {
		if (err) throw err;
		if (stats.isSymbolicLink()) return;
		if (stats.isFile()) {
			if (!file.endsWith('.js')) return;
			fs.readFile(file, "utf-8", (err, text) => {
					if (err) throw err;
					var anyMatch = false;
					for (var i = 0; i < replacements.length; i++) {
						anyMatch = anyMatch || text.match(replacements[i].regex);
						if (anyMatch) text = text.replace(replacements[i].regex, replacements[i].replace);
					}
					if (!anyMatch) return;
					fs.writeFile(file, text, err => {
						if (err) throw err;
					});
				});
		} else if (stats.isDirectory()) {
			fs.readdir(file, (err, files) => {
				if (err) throw err;
				for (var i = 0; i < files.length; i++) {
					replace(path.join(file, files[i]), replacements);
				}
			});
		}
	});
}

const HEAD = path.resolve(__dirname, 'HEAD');
const submodule = path.resolve(__dirname, 'vendor/pokemon-showdown');
const sim = path.resolve(__dirname, 'sim');
const data = path.resolve(__dirname, 'data');

const FILES = new Set(tree(sim).map(m => m.slice(sim.length + 1)));
const OVERRIDDEN = new Set([
  'package.json',
  'README.md',
  'sim/chat.ts',
  'sim/global-types.ts',
  'sim/global-variables.d.ts',
  'sim/index.ts',
  'test/main.js',
  'tsconfig.json',
]);
const COPIED = [...FILES].filter(f => !OVERRIDDEN.has(f));

const interesting = f => {
  if (f.startsWith('sim') || f.startsWith('test/sim')) return true;
  if (f.startsWith('data') && !f.endsWith('random-teams.js')) return true;
  return COPIED.has(f);
}

(async () => {
  await execOrDie('npm install @pkmn/types);
  await execOrDie('git submodule update --remote --rebase');
  const now = (await execOrDie('git rev-parse HEAD', submodule)).slice(0, 8);
  const last = fs.readFileSync(HEAD, 'utf-8').trim();

  const changed = (await execOrDie(`git diff --name-only ${last}..${now}`, submodule)).split
  ('\n');
  console.log(`https://github.com/smogon/pokemon-showdown/compare/${last}..${now}`);
  for (const change of changed) {
    if (!change) continue;
    if (interesting(change)) {
      console.log('\x1b[91mCHANGED\x1b[0m', change);
    }
  }

  for (const file of COPIED) {
    fs.copyFileSync(path.resolve(submodule, file), path.resolve(sim, file));
  }

  fs.writeFileSync(HEAD, now);
})().catch(console.error);