#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const subPackages = {};
for (const pkg of require('./package.json').subPackages) {
  const json = require(path.join(__dirname, pkg, 'package.json'));
  subPackages[json.name] = { path: pkg, json };
}

for (const n in subPackages) {
  const pkg = subPackages[n];
  let nl = false;
  for (const dep of ['dependencies', 'devDependencies', 'optionalDependencies']) {
    if (pkg.json[dep]) {
      for (const name in pkg.json[dep]) {
        const internal = subPackages[name];
        if (internal) {
          if (!nl) console.log(`\x1b[96m${pkg.json.name}\x1b[0m`);
          nl = true;

          const from = `${pkg.path}/node_modules/${name}`;
          const to = path.relative(`${pkg.path}/node_modules/@pkmn`, internal.path);
          console.log(`\x1b[90m${name}\x1b[0m ${from} -> ${to}`);

          try {
            fs.unlinkSync(from);
          } catch (err) {
            if (err.code !== 'ENOENT') throw err;;
          }
          fs.symlinkSync(to, from);
        }
      }
    }
  }
  if (nl) console.log();
}