#!/usr/bin/env node
'use strict';

try {
  require('source-map-support').install();
} catch (err) {
  if (err.code !== 'MODULE_NOT_FOUND') throw err;
}

const {Protocol} = require('./build');

const contents = process.argv[2] ? process.argv[2] : ' ';

for (const arg in Protocol.ARGS) {
  if (Protocol.ARGS_WITH_KWARGS[arg]) {
    console.log(`'${arg}'(args: Args['${arg}'], kwArgs: KWArgs['${arg}']) {${contents}}`);
  } else {
    console.log(`'${arg}'(args: Args['${arg}']) {${contents}}`);
  }
}