#!/usr/bin/env node

const {Protocol} = require('./build');

for (const arg in Protocol.ARGS) {
  if (Protocol.ARGS_WITH_KWARGS[arg]) {
    console.log(`'${arg}'(args: Args['${arg}'], kwArgs: KWArgs['${arg}']) { }`);
  } else {
    console.log(`'${arg}'(args: Args['${arg}']) { }`);
  }
}