#!/usr/bin/env node
'use strict';

const Bundler = require('../bundler');
const bundler = new Bundler(__dirname);

let bundled = `(() => {
'use strict';
const exports = {};
`;
bundled += bundler.read('sets.js', 3, 1);
bundled += 'const sets_1 = exports;\n';
bundled += bundler.read('teams.js', 4, 1);
bundled += `
// EXPORTS
window.PokemonSets = exports.Sets;
window.PokemonTeams = exports.Teams;
})();`
bundler.bundle(bundled).catch(err => {
  console.log(err);
  process.exit(2);
});
