#!/usr/bin/env node
'use strict';

const Bundler = require('../bundler');
const bundler = new Bundler(__dirname);

let bundled = `(() => {
'use strict';
const exports = {};
`;
const gen = bundler.read('index.js').split('\n');
bundled += gen.slice(1, 13).join('\n'); // polyfill
bundled += gen.slice(14, -1).join('\n'); // code
bundled += `
// EXPORTS
window.Generations = exports.Generations;
})();`
bundler.bundle(bundled).catch(err => {
  console.log(err);
  process.exit(2);
});
