#!/usr/bin/env node
'use strict';

const Compiler = require('../compiler');
const compiler = new Compiler(__dirname);

let bundled = `(() => {
'use strict';
const exports = {};
`;
const gen = compiler.read('gen.js').split('\n');
bundled += gen.slice(1, 13).join('\n'); // polyfill
bundled += gen.slice(15, -1).join('\n'); // code
bundled += `
// EXPORTS
window.Generations = exports.Generations;
})();`
compiler.compile(bundled);
