#!/usr/bin/env node
'use strict';

const child_process = require('child_process');
const path = require('path');
const minimist = require('minimist');

const argv = minimist(process.argv.slice(2));
const shell = (cmd, cwd = __dirname) => child_process.execSync(cmd, {stdio: 'inherit', cwd});

// Tracks whether some promises threw errors that weren't caught so we can log
// and exit with a non-zero status to fail any tests. This "shouldn't happen"
// because we're "great at propagating promises (TM)", but better safe than sorry.
const RejectionTracker = new class {
  constructor() {
    this.unhandled = [];
  }

  onUnhandledRejection(reason, promise) {
    this.unhandled.push({ reason, promise });
  }

  onRejectionHandled(promise) {
    this.unhandled.splice(this.unhandled.findIndex(u => u.promise === promise), 1);
  }

  onExit(code) {
    let i = 0;
    for (const u of this.unhandled) {
      const error = (u.reason instanceof Error) ? u.reason :
        new Error(`Promise rejected with value: ${u.reason}`);
      console.error(`UNHANDLED PROMISE REJECTION:\n${error.stack}`);
      i++;
    }
    process.exit(code + i);
  }

  register() {
    process.on('unhandledRejection', (r, p) => this.onUnhandledRejection(r, p));
    process.on('rejectionHandled', p => this.onRejectionHandled(p));
    process.on('exit', c => this.onExit(c));
  }
}();

RejectionTracker.register();

const ExhaustiveRunner = (() => {
  if (argv._[0] === 'sim') {
    const PS = '../vendor/pokemon-showdown';
    shell('npm install && node build', path.resolve(__dirname, PS));
    return require('./src/text/sim');
  } else if (argv._[0] === 'client') {
    const PSC = '../vendor/pokemon-showdown-client';
    shell('npm install && node build indexes', path.resolve(__dirname, PSC));
    return require('./src/text/client');
  } else {
    console.error(`Unrecognized mode: ${argv._[0]}\n`);
    process.exit(1);
  }
})();

let formats;
if (argv.formats) {
  formats = argv.formats.split(',');
} else if (argv.format) {
  formats = argv.format.split(',');
} else {
  formats = ExhaustiveRunner.FORMATS;
}
let cycles = Number(argv._[1] || argv.cycles) || ExhaustiveRunner.DEFAULT_CYCLES;
let forever = argv.forever;
if (cycles < 0) {
  cycles = -cycles;
  forever = true;
}
const maxFailures =
  argv.maxFailures || argv.failures || (formats.length > 1 ? ExhaustiveRunner.MAX_FAILURES : 1);
const prng = argv.seed && argv.seed.split(',').map(s => Number(s));
const log = true;
const cmd = (cycles, format, seed) =>
  `node integration/test ${argv._[0]} --cycles=${cycles} --format=${format} --seed=${seed}`;
(async () => {
  let failures = 0;
  do {
    for (let format of formats) {
      failures += await new ExhaustiveRunner({format, cycles, prng, maxFailures, log, cmd}).run();
      process.stdout.write('\n');
      if (failures >= maxFailures) break;
    }
  } while (forever);
  process.exit(failures);
})();