#!/usr/bin/env node
'use strict';

const Bundler = require('../bundler');
const bundler = new Bundler(__dirname);

let bundled = `(() => {
'use strict';
const exports = {};
`;
bundled += `const DATA = ${bundler.read('data/data.json')};\n`;
bundled += bundler.read('data/index.js', 24, 1);
bundled += bundler.read('adaptable.js', 3, 1);
bundled += `
// EXPORTS
window.PokemonSprites = new exports.Sprites(exports.Data);
window.PokemonIcons = new exports.Icons(exports.Data);
})();`
bundler.bundle(bundled).catch(err => {
  console.log(err);
  process.exit(2);
});
