#!/usr/bin/env node
'use strict';

const Bundler = require('../bundler');
const bundler = new Bundler(__dirname);

let bundled = `(() => {
'use strict';
const exports = {};
`;
bundled += `const DATA = ${bundler.read('data/data.json')};\n`;
bundled += bundler.read('data/index.js', 24, 1);
bundled += bundler.read('adaptable.js', 3, 1);
bundled += `
// EXPORTS
window.PokemonSprites = new exports.Sprites(exports.Data);
window.PokemonSprites.SOURCES = exports.Sprites.SOURCES;
window.PokemonSprites.GENS = exports.Sprites.GENS;
window.PokemonSprites.ANIMATED = exports.Sprites.ANIMATED;
window.PokemonSprites.FRAME2 = exports.Sprites.FRAME2;
window.PokemonIcons = new exports.Icons(exports.Data);
})();`
bundler.bundle(bundled);